apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.ingress.name }}
  labels: 
    description: {{ default (printf "%s-ingress" .Chart.Name) .Values.ingress.name | trunc 63 | trimSuffix "-" }}
    chart: {{ default (printf "%s-ingress" .Chart.Name) .Values.ingress.chartName | trunc 63 | trimSuffix "-" }}
  annotations:
    nginx.ingress.kubernetes.io/configuration-snippet: |-
      add_header X-Content-Type-Options "nosniff";
      add_header X-DNS-Prefetch-Control "off";
      add_header X-Download-Options "noopen";
      add_header X-Frame-Options "deny";
      add_header X-Permitted-Cross-Domain-Policies "none";
      add_header Example-String {{ include "nested-headers.csp" (.Values.ingress.exampleString | default "none") | quote }};
      add_header Example-List {{ .Values.ingress.exampleList | join " " | quote }};
      {{- range $k, $v := .Values.ingress.headers }}
      add_header {{ $k }} {{ include "nested-headers.csp" $v | quote }};
      {{- end }}
spec:
  rules:
    - host: app.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: example-service
                port:
                  number: 80
