apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/configuration-snippet: |-
      add_header X-Permitted-Cross-Domain-Policies "none";
      add_header Example-String {{ include "nested-headers" (.Values.ingress.exampleString | default "none") | quote }};
      add_header Example-List {{ .Values.ingress.exampleList | join " " | quote }};
      {{- range $k, $v := .Values.ingress.headers }}
      add_header {{ $k }} {{ include "nested-headers" $v | quote }};
      {{- end }}
    {{- range .Values.ingress.annotations }}
    {{ toYaml . }}
    {{- end }}
  labels: 
    description: {{ default (printf "%s-ingress" .Chart.Name) .Values.ingress.nameOverride | trunc 63 | trimSuffix "-" }}
    chart: {{ default (printf "%s-ingress" .Chart.Name) .Values.ingress.chartName | trunc 63 | trimSuffix "-" }}
  name: {{ required "A name for the ingress is required, please put nameOverride with a value in the values.yaml" .Values.ingress.nameOverride | quote }}
spec:
  rules:
    - host: app.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: example-service
                port:
                  number: 80
