ingress:
  nameOverride: "vitiate"
  exampleString: "foo"
  exampleList:
    - bar
    - baz
  tlsEnabled: true
  whitelist_select: "generic"
  annotations:
    - nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    - nginx.ingress.kubernetes.io/proxy-connect-timeout: "60"
    - nginx.ingress.kubernetes.io/proxy-read-timeout: "60"
    - nginx.ingress.kubernetes.io/ssl-redirect: "true"
    - nginx.ingress.kubernetes.io/use-regex: "true"
  headers:
    X-Content-Type-Options: "nosniff"
    X-DNS-Prefetch-Control: "off"
    X-Download-Options: "noopen"
    X-Frame-Options: "deny"
    Referrer-Policy: no-referrer
    Content-Security-Policy:
      frame-ancestors:
        - "'self'"
      default-src:
        - "'self'"
        - "'unsafe-inline'"
        - "*.company.com"
        - "*.service.com"
      img-src:
        - "'self'"
        - "'unsafe-inline'"
        - "*.privacy-service.org"
        - "*.trust-service.com"
        - "data:"
        - "https://*.service.com"
        - "https://*.feedback-service.com"
        - "https://ad.analytics-provider.net/ddm/activity/"
        - "https://adservice.search-engine.com"
        - "https://metrics.company.com"
      script-src:
        - "'self'"
        - "'unsafe-eval'"
        - "'unsafe-inline'"
        - "*.privacy-service.org"
        - "*.trust-service.com"
        - "https://*.analytics-service.net/"
        - "https://*.company.com"
        - "https://*.feedback-service.com"
        - "https://assets.tag-manager.com/"
        - "https://cdn.personalization-service.net/company.js"
        - "https://edge.analytics-cloud.net/"
        - "https://company.personalization-service.net/"
        - "https://www.search-engine.com/recaptcha/"
        - "https://www.static-content.com/recaptcha/"
      style-src:
        - "'self'"
        - "'unsafe-inline'"
        - "https://*.company.com"
        - "https://*.feedback-service.com"
      frame-src:
        - "'self'"
        - "*.trust-service.com"
        - "https://*.feedback-service.com"
        - "https://company.analytics-service.net/"
        - "https://www.search-engine.com/recaptcha/"
        - "https://www.video-platform.com/"
      connect-src:
        - "'self'"
        - "*.privacy-service.org"
        - "*.trust-service.com"
        - "https://*.analytics-service.net/"
        - "https://*.service.com"
        - "https://*.feedback-service.com"
        - "https://edge.analytics-cloud.net/"
        - "https://company.personalization-service.net/"
        - "https://metrics.company.com/"
      font-src:
        - "'self'"
        - "*.feedback-service.com"
        - "data:"
        - "https://*.company.com"
      report-uri: "https://some.example.com/gateway/api-gateway/api/gateway/csp-reporting"
      report-to: "'csp-endpoint'"
    Report-To: "{ \"group\": \"csp-endpoint\", \"max-age\": 10886400, \"endpoints\": [{ \"url\": \"https://example.com/csp-reporting\"}] }"
    Feature-Policy:
      camera: "'none'"
      microphone: "'none'"
      geolocation: "'none'"
      encrypted-media: "'none'"
      payment: "'none'"
      speaker: "'none'"
      usb: "'none'"
    